M48
; DRILL file {KiCad 8.0.7-8.0.7-0~ubuntu22.04.1} date 2025-02-05T23:47:47-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-05T23:47:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7-8.0.7-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X139.0Y-73.0
X139.0Y-133.0
X157.0Y-73.0
X157.0Y-133.0
M30
